import { Product } from './types';

export const products: Product[] = [
  {
    id: 'classic-chocolate-chip',
    nameKey: 'cookie.classic_chip.name',
    descriptionKey: 'cookie.classic_chip.desc',
    price: 12.50,
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&q=80&w=800',
    category: 'signature',
    tags: ['bestseller'],
    isBestSeller: true,
  },
  {
    id: 'double-chocolate-delight',
    nameKey: 'cookie.double_choco.name',
    descriptionKey: 'cookie.double_choco.desc',
    price: 15.90,
    rating: 4.8,
    reviewsCount: 98,
    image: 'https://images.unsplash.com/photo-1558961312-503cd6b6efbc?auto=format&fit=crop&q=80&w=800',
    category: 'signature',
    tags: ['bestseller'],
    isBestSeller: true,
  },
  {
    id: 'zen-matcha-white-chocolate',
    nameKey: 'cookie.matcha_zen.name',
    descriptionKey: 'cookie.matcha_zen.desc',
    price: 15.90,
    rating: 4.9,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1530648672449-81fc504100a9?auto=format&fit=crop&q=80&w=800',
    category: 'signature',
    tags: ['new'],
  },
  {
    id: 'red-velvet-dream',
    nameKey: 'cookie.red_velvet.name',
    descriptionKey: 'cookie.red_velvet.desc',
    price: 18.90,
    rating: 4.7,
    reviewsCount: 114,
    image: 'https://images.unsplash.com/photo-1618923850107-d1a234d7a73a?auto=format&fit=crop&q=80&w=800',
    category: 'classic',
    tags: [],
  },
  {
    id: 'golden-almond-crunch',
    nameKey: 'cookie.almond_crunch.name',
    descriptionKey: 'cookie.almond_crunch.desc',
    price: 18.90,
    rating: 4.9,
    reviewsCount: 82,
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=800',
    category: 'crunchy',
    tags: ['new'],
  },
  {
    id: 'creamy-peanut-butter',
    nameKey: 'cookie.peanut_butter.name',
    descriptionKey: 'cookie.peanut_butter.desc',
    price: 12.50,
    rating: 4.6,
    reviewsCount: 48,
    image: 'https://images.unsplash.com/photo-1568254183919-78a4f43a2877?auto=format&fit=crop&q=80&w=800',
    category: 'classic',
    tags: [],
  },
  {
    id: 'healthy-oatmeal-raisin',
    nameKey: 'cookie.oatmeal_raisin.name',
    descriptionKey: 'cookie.oatmeal_raisin.desc',
    price: 8.90,
    rating: 4.5,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1600431521340-491eca880813?auto=format&fit=crop&q=80&w=800',
    category: 'classic',
    tags: [],
  },
  {
    id: 'white-chocolate-macadamia',
    nameKey: 'cookie.macadamia.name',
    descriptionKey: 'cookie.macadamia.desc',
    price: 18.90,
    rating: 4.8,
    reviewsCount: 125,
    image: 'https://images.unsplash.com/photo-1558961314-bc8a4d49ec2c?auto=format&fit=crop&q=80&w=800',
    category: 'crunchy',
    tags: [],
  }
];
